---
- name: Example Playbook
  hosts: localhost
  tasks:
    - name: Print secret length instead of value
      ansible.builtin.debug:
        msg: |
          "The secret has been retrieved and has a length of {{ beta_secret | length }} characters."
