name: Azure Key Vault Secrets Example

on: [push]

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secrets from Azure Key Vault
        id: get-secrets
        run: |
          SECRET_VALUE=$(az keyvault secret show --name aznpadevkey --vault-name ${{ secrets.AZURE_KEYVAULT_NAME }} --query value -o tsv)
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Execute Ansible playbook
        run: ansible-playbook playbook.yml -vvv --extra-vars "beta_secret=${{ env.SECRET_VALUE }}"
