name: CI/CD Pipeline with Ansible Checks

on:
  push:
    branches:
      - main
      - fix/actions

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secrets from Azure Key Vault
        id: get-secrets
        env:
          AZ_KEYVAULT_NAME: ${{ secrets.AZ_KEYVAULT_NAME }}
          AZ_VAULT_NAME: ${{ secrets.AZ_VAULT_NAME }}
        run: |
          set -euo pipefail
          SECRET_VALUE=$(az keyvault secret show \
            --name "${AZ_KEYVAULT_NAME}" \
            --vault-name "${AZ_VAULT_NAME}" \
            --query value -o tsv)
          
          if [[ -z "$SECRET_VALUE" ]]; then
            echo "Error: No value retrieved from Azure Key Vault" >&2
            exit 1
          fi
          
          echo "::add-mask::$SECRET_VALUE"
          echo "BETA=$SECRET_VALUE" >> $GITHUB_ENV

      - name: Print Secret (for debugging purposes)
        run: echo "The secret value is set and masked."

  ansible-checks:
    runs-on: ubuntu-latest
    needs: fetch-secrets
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Python and create virtual environment
        run: |
          set -eEuo pipefail

          sudo apt-get update -yqq && sudo apt-get install -yqq python3-venv

          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install ansible ansible-core ansible-lint

      - name: Run Ansible Lint
        run: |
          set -eEuo pipefail

          source .venv/bin/activate
          ansible --version
          ansible-lint playbook.yml

      - name: Execute Ansible playbook
        run: |
          set -eEuo pipefail

          source .venv/bin/activate
          ansible-playbook playbook.yml -v --extra-vars "beta_secret=${BETA}"
